main: me.fenixra.magic_altar.Main
name: MagicAltar
version: 1.4
author: FenixRa
website: https://www.spigotmc.org/resources/104593/
commands:
  altar:
    description: altar cmd
    usage: /altar [args]