main: me.fenixra.magic_altar.Main
name: MagicAltar
version: 1.0
author: PhoenixRa
website: https://www.spigotmc.org/resources/100438/
depend: [HolographicDisplays]
commands:
  altar:
    description: altar cmd
    usage: /altar [args]